/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.mmdc.test;





public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       java.awt.EventQueue.invokeLater(()->{
           new LoginFrame().setVisible(true);
       });
    }
}
